modLoader="javafml"
loaderVersion="[4,)"

license="GPL3"

[[mods]]
modId="youbuild"
version="1.1.0"
displayName="YouBuild"
authors="YourName"
description='''Structure building assistant mod'''

# 正确声明依赖
[[dependencies.youbuild]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.youbuild]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.youbuild]]
modId="blockui"
type="required"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.youbuild]]
modId="domum_ornamentum"
type="required"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"

[[dependencies.youbuild]]
modId="structurize"
type="required"
versionRange="[1,)"
ordering="AFTER"
side="BOTH"